### ISSUE TITLE
Reader View

### ISSUE THREAD

**Issue by robert-baldwin** [robert-baldwin/reader-app#1]
## Purpose
1. Read the original content
2. Extract an excerpt of the text for later use

## Wireframe
![Highlight w_ Create Excerpt Button](https://user-images.githubusercontent.com/2874078/70116696-4cb24880-1618-11ea-94f1-112078bf6570.png)

## Styling
1. Maximum text width is 2/3rds of the viewport
2. All excerpts have the same background color
3. Focused excerpts have a different background color

## Behaviors
1. When a user selects a portion of text -> then a _create excerpt_ icon is shown
2. When the _create excerpt_ icon is clicked -> then an excerpt is created with the selected text and the selection is cleared
3. When the _search excerpts_ icon is clicked -> then the _Excerpts Search Panel_ is shown
4. When an _excerpt_ is clicked -> then the _Annotation Panel_ is shown and the excerpt is focused
5. When an _excerpt_ is focused -> then the excerpt is scrolled into view
6. When a mouse hovers over a focused _excerpt_ -> then the _remove excerpt_ icon* is shown
7. When the _remove excerpt_ icon is clicked -> then the excerpt is deleted

*Shown in the _Annotation Panel_ (https://github.com/robert-baldwin/reader-app/issues/3) wireframe

**Comment by gdbaldw** [comment]
e388257340585368e9a4e38342e46cbe487720f4 fundamentally addresses behaviors 1, 2 (but is kept selected for now?), 4 focus, 6 (but icon is permanent), and 7. The button location must overlay  Range start, so will need to create custom icon that are transparent at the text location. The "body" remains unchanged, and I believe can include a tree of elements. The key restriction of this method, as mentioned above, is that the icon location must be coincident with the Range start. Next, will tackle refactoring annotations.

**Comment by gdbaldw** [comment]
My understanding was that the excerpts would be highlighted only when in Excerpt Search mode, but that in Reader mode the text would be without highlights. It appears to me currently the excerpts all are highlighted at all times. I've received user feedback that the highlights at all times could be distracting, and also that the default Excerpt Search view listing all excerpts in sequential order would be helpful. Also, I'm curious about why hash instead of a sequence id for each excerpt.
